# Generated by Django 5.0.4 on 2024-04-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobberApp', '0002_auto_20240325_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.TextField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Job',
        #     fields=[
        #         ('job_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('job_title', models.CharField(max_length=100)),
        #         ('job_url', models.URLField()),
        #         ('job_location', models.CharField(max_length=100)),
        #         ('job_description', models.TextField()),
        #         ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobberApp.company')),
        #     ],
        # ),
    ]
