# Generated by Django 5.0.4 on 2024-04-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobberApp', '0004_applications'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='job',
        #     old_name='company',
        #     new_name='company_id',
        # ),
    ]
