# Generated by Django 5.0.4 on 2024-04-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobberApp", "0006_rename_company_id_job_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        # migrations.RemoveField(
        #     model_name="job",
        #     name="company",
        # ),
        # migrations.DeleteModel(
        #     name="UserDetails",
        # ),
        migrations.AlterModelOptions(
            name="applications",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"managed": False},
        ),
        # migrations.DeleteModel(
        #     name="Job",
        # ),
    ]
