# Generated by Django 5.0.4 on 2024-04-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobberApp", "0007_users_remove_job_company_delete_userdetails_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="applications",
            table="applications",
        ),
        migrations.AlterModelTable(
            name="company",
            table="company",
        ),
    ]
