# Generated by Django 4.2.11 on 2024-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('jobUrl', models.TextField()),
                ('companyName', models.TextField()),
                ('location', models.TextField()),
                ('jobDescription', models.TextField()),
            ],
        ),
    ]
