# Generated by Django 5.0.4 on 2024-04-15 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
                ("company_description", models.TextField()),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=100)),
                ("job_URL", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("max_salary", models.DecimalField(decimal_places=0, max_digits=10)),
                ("min_salary", models.DecimalField(decimal_places=0, max_digits=10)),
                ("location", models.CharField(max_length=100)),
                ("date_applied", models.DateField()),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("job_description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="JobberApp.users",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
            },
        ),
    ]
