# Generated by Django 5.0.4 on 2024-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobberApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="company",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="date_applied",
            field=models.DateField(default="2024-10-20", null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="follow_up_date",
            field=models.DateField(blank=True, default="2024-10-20", null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="job_URL",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="job_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="max_salary",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="min_salary",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
