# Generated by Django 5.0.4 on 2024-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobberApp", "0002_alter_applications_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("contact_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, null=True)),
                ("loc", models.CharField(max_length=100, null=True)),
                ("desc", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(max_length=100, null=True)),
                ("company", models.CharField(max_length=100, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("relationship", models.CharField(max_length=100, null=True)),
                ("link", models.CharField(max_length=100, null=True)),
                (
                    "follow_up_date",
                    models.DateField(blank=True, default="2024-10-20", null=True),
                ),
            ],
            options={
                "db_table": "contacts",
            },
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_name",
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
