# Generated by Django 5.0.4 on 2024-04-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobberApp", "0003_contacts_remove_company_company_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacts",
            old_name="name",
            new_name="fullName",
        ),
        migrations.RenameField(
            model_name="contacts",
            old_name="desc",
            new_name="linkedIn",
        ),
        migrations.RenameField(
            model_name="contacts",
            old_name="link",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="loc",
        ),
        migrations.AddField(
            model_name="contacts",
            name="goal",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
