# Generated by Django 5.0.4 on 2024-04-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobberApp", "0004_rename_name_contacts_fullname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacts",
            old_name="follow_up_date",
            new_name="followUpDate",
        ),
        migrations.RenameField(
            model_name="contacts",
            old_name="linkedIn",
            new_name="linkedin",
        ),
    ]
