# Generated by Django 5.0.4 on 2024-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobberApp', '0005_rename_company_job_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
    ]
